version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=map1
      - PGPASSWORD=7632
      - PGPORT=5432
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7632
      - POSTGRES_DB=map1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: